server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-rest-customers
          uri: lb://api-rest-customers
          predicates:
            - Path=/api/customers/**
        - id: api-rest-accounts
          uri: lb://api-rest-accounts
          predicates:
            - Path=/api/accounts/**
        - id: api-rest-credits
          uri: lb://api-rest-credits
          predicates:
            - Path=/api/credit/**
        - id: api-rest-credit-cards
          uri: lb://api-rest-credit-cards
          predicates:
            - Path=/api/credit-card/**
        - id: api-rest-transactions
          uri: lb://api-rest-transactions
          predicates:
            - Path=/api/transactions/**
